In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Se importa el archivo como .CSV y se lo guarda en un set de datos.

In [34]:
df = pd.read_csv("Trabajo Integrador - Estadistica - Datos Brutos.csv", skiprows=2)
df = df.drop(columns=["Unnamed: 2"])
df.head()

   Horas de  consumo de redes sociales por día  Rendimieno académico
0                                            5                     7
1                                            1                     8
2                                            3                     8
3                                            3                     8
4                                            6                     7

# Se ajusta el nombre de las variables para hacerlas más accesibles

In [35]:
df = df.rename(columns={"Horas de  consumo de redes sociales por día": "x", "Rendimieno académico": "y"})
df.head()

   x  y
0  5  7
1  1  8
2  3  8
3  3  8
4  6  7